"""add last_activity_at to users

Revision ID: 5579c4c0aae2
Revises: fb7deae5566c
Create Date: 2026-01-04 13:01:57.351009
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5579c4c0aae2'
down_revision = 'fb7deae5566c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
