"""add feedback table

Revision ID: 8bc27fdeb034
Revises: 0005_drop_settlement_type
Create Date: 2026-01-04 12:01:30.120568
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc27fdeb034'
down_revision = '0005_drop_settlement_type'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
