"""add last_activity_at to users

Revision ID: fb7deae5566c
Revises: 8bc27fdeb034
Create Date: 2026-01-04 12:37:06.655320
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7deae5566c'
down_revision = '8bc27fdeb034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_users_last_activity', 'users', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_users_last_activity_at'), 'users', ['last_activity_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_activity_at'), table_name='users')
    op.drop_index('ix_users_last_activity', table_name='users')
    op.drop_column('users', 'last_activity_at')
    # ### end Alembic commands ###
